samples:
  # update your samples.txt file with the paths to R1 and R2
  'resources/config/samples.txt'

units: resources/config/units.txt

binning: resources/config/binning.txt

reads:
  - R1
  - R2

assemblers:
  - metaspades
  - megahit

biobakery:
  - metaphlan

params:
  cutadapt:
    adapter: 'GATCGGAAGAGC'
    other: "--minimum-length 1 --nextseq-trim 20"
  multiqc: ''
  bowtie2:
    bt2_command: 'bowtie2'
    bt2b_command: 'bowtie2-build'
    extra: '--very-fast'
  sourmash:
    k: 31
    scaled: 1000
    extra: ''
  metaphlan:
    db_path: "resources/db/metaphlan"
    db_name: "mpa_v30_CHOCOPhlAn_201901"
    other: "--add_viruses --unknown_estimation"
  concoct:
    chunk_size: 10000
    overlap_size: 0
  minimap2:
    k: 500000000

threads:
  fastqc: 1
  cutadapt_pe: 4
  fastqc_post_trim: 1
  host_filter: 4
  spades: 8
  megahit: 8
  metaphlan: 4
  bowtie2_build: 8
  map_reads: 1
  sort_bam: 1
  minimap2_index: 4
  minimap2_map_reads: 4

mem_mb:
  spades: 256000
  megahit: 256000

host_filter:
  db_dir: resources/db/bt2
  accn: GCA_000001405.28
  # NCBI GenBank Accession number for the host genome assembly.
  # This will be automatically downloaded and indexed in the location
  # {db_dir}/{accn}.
  # Some Useful Accession Numbers:
  # Latest builds as of 12-July-2021
  # Genome Reference Consortium Human Build 38 patch release 13 (GRCh38.p13)
  # accn: GCA_000001405.28
  # Genome Reference Consortium Mouse Build 39
  # accn: GCA_000001635.9
  # Setophaga coronata coronata (myrtle warbler) (mywa_2.1) - Cornell University
  # accn: GCA_001746935.2
