samples:
  # update your samples.txt file with the paths to R1 and R2
  'resources/config/samples.txt'

units: resources/config/units.txt

reads: 
  - R1
  - R2

assemblers:
  - metaspades
  - megahit

params:
  cutadapt:
    adapter: 'GATCGGAAGAGC'
    other: "--minimum-length 1 --nextseq-trim 20"
  multiqc: ''
  bowtie2: ''
  sourmash:
    k: 31
    scaled: 1000
    extra: ''

threads:
  fastqc: 1
  cutadapt_pe: 4
  fastqc_post_trim: 1
  host_filter: 4
  spades: 8
  megahit: 8

mem_mb:
  spades: 10000
  megahit: 10000

host_filter:
  db_dir: resources/test/test_dbs
  accn: GCA_000001635.9 
  # NCBI GenBank Accession number for the host genome assembly.
  # This will be automatically downloaded and indexed in the location
  # {db_dir}/bt2/{host_accn}.

  # To bypass this and use an existing bt2 index, 
  # To use 
  # Local:
  # bt2_path: '/Users/danielsprockett/db/bt2/GCF_000001635.27_GRCm39_genomic'
  # cbsumoeller@biohpc.cornell.edu:
  # bt2_path:  /workdir/dbs/bowtie2/Mm_GRCm39
